from my_library.models.hotpot_legacy import BidirectionalAttentionFlow
# from my_library.models.hotpot_legacy_rl import RLBidirectionalAttentionFlow
from my_library.models.hotpot_decoupled import BidirectionalAttentionFlow
