from my_library.models.academic_paper_classifier import AcademicPaperClassifier
from my_library.models.hotpot_legacy import BidirectionalAttentionFlow
from my_library.models.hotpot_legacy_rl import RLBidirectionalAttentionFlow
from my_library.models.hotpot_legacy_labelchain2gate import Chain2GateBidirectionalAttentionFlow
from my_library.models.hotpot_legacy_gate import GateBidirectionalAttentionFlow
from my_library.models.hotpot_legacy_ptn_chain import PTNChainBidirectionalAttentionFlow
