from my_library.models.academic_paper_classifier import AcademicPaperClassifier
from my_library.models.hotpot_legacy import BidirectionalAttentionFlow
from my_library.models.hotpot_decoupled import BidirectionalAttentionFlow